<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" dir="ltr">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<title>{{ title }}</title>
	<link href="css/style.css" rel="stylesheet" type="text/css" />
</head>
<body>
	<div id="welcome">
	    <h1>Welcome to the<span id="zf-name">Zend Framework!</span></h1>

		<div id="hello">Hello {{ user }} @ {{ host }}<br />
		This is your project's main page and<br />
		it was rendered using <a href="http://www.twig-project.org" class="white">Twig</a> template engine.
		</div>

	    <div id="more-information">
	        <p>
	            <span id="links">Helpful links for you {{ user }}:</span>
	            <a href="http://framework.zend.com/">Zend Framework Website</a> &#x2665;
	            <a href="http://framework.zend.com/manual/en/">Zend Framework Manual</a>
	        </p>

	        <div id="powered_by">
	        	<a href="http://framework.zend.com/"><img src="images/PoweredBy_ZF_4LightBG.png" alt="Zend Framework" /></a>
	        </div>
	    </div>
	</div>
</body>
</html>
