<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" dir="ltr">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<title>{{ title }}</title>
	<link href="css/style.css" media="screen" rel="stylesheet" type="text/css" />
</head>
<body>
	<div id="welcome">
	    <h1>Welcome to the<div id="zf-name">Zend Framework!</div></h1>

		<div id="hello">Hello {{ user }} @ {{ ip }}<br />This is your project's main page</div>

	    <div id="more-information">
	        <p>
	            <span id="links">Helpful links for you {{ user }}:</span>
	            <a href="http://framework.zend.com/">Zend Framework Website</a> &#x2665;
	            <a href="http://framework.zend.com/manual/en/">Zend Framework Manual</a>
	        </p>

	        <div id="powered_by"><img src="http://framework.zend.com/images/PoweredBy_ZF_4LightBG.png" /></div>
	    </div>
	</div>
</body>
</html>
